---
k3s_version: v1.23.6+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['tag_role_master'][0]]['ansible_host'] | default(groups['tag_role_master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
