---

- hosts: tag_app_k3s
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: tag_role_master
  become: yes
  roles:
    - role: k3s/master

- hosts: tag_role_worker-1
  become: yes
  roles:
    - role: k3s/node

- hosts: tag_role_worker-2
  become: yes
  roles:
    - role: k3s/node

